# Compiler
CC = gcc

# Compiler Flags
CFLAGS = -Wall -g

# Linker Flags
LDFLAGS = -lGL -lglfw -ldl

# Source Files
SRCS = glad.c main.c ogl.c shaders.c

# Object Files
OBJS = $(SRCS:.c=.o)

# Executable Name
EXEC = demo_app

# Defaul1t Target
all: $(EXEC)

# Link Object Files to Create Executable
$(EXEC): $(OBJS)
	$(CC) $(OBJS) -o $(EXEC) $(LDFLAGS)

# Compile Source Files to Object Files
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# Clean Target
clean:
	rm -f $(OBJS) $(EXEC)

# Phony Targets
.PHONY: all clean
